# docker installation

- name: add docker key
  rpm_key:
    key: "https://download.docker.com/linux/centos/gpg"
    state: present

- name: add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker-ce & epel-relase
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: install py dependencies
  yum:
    update_cache: yes
    name: python3-pip
    state: latest

- name: install docker sdk for py
  pip:
    name: docker